import { Layout } from "../../components/Layout";
import {} from "./styles.module.scss";

const Registration: React.FC = () => {
  return (
    <Layout
      heading="Cadastro de Produtos"
      title="Generated by created product"
      type={"dashboard"}
    >
      <section>
        <h1>Section</h1>
      </section>
    </Layout>
  );
};

export default Registration;
